export enum IncidentType {
  MISCONDUCT = 'MISCONDUCT',
  ABSENTEEISM = 'ABSENTEEISM',
  VIOLENCE = 'VIOLENCE',
  SUBSTANCE_ABUSE = 'SUBSTANCE_ABUSE',
  INSUBORDINATION = 'INSUBORDINATION',
  BULLYING = 'BULLYING',
  ACADEMIC_DISHONESTY = 'ACADEMIC_DISHONESTY',
  OTHER = 'OTHER',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  ESCALATED = 'ESCALATED',
}
